### ISSUE TITLE
Besprechungstreffen eures Projekts

### ISSUE THREAD

**Issue by MrOerni** [ProPra16/programmierpraktikum-abschlussprojekt-never-surrender-1#1]
Hallo,

Bitte sprecht mit mir einen Termin ab, wo ihr mir euer Projekt vorstellt, in eurem derzeitigen Zustand.
Von Problemen und Lösungen berichtet oder zu bestehenden Themen fragen stellt.

Der Termin sollte höchstens 30min lang sein. Es geht nur darum, zu sehen was ihr wie macht.

Gruß,

Björn

**Comment by Arucis** [comment]
Wir haben einen Raum in der Naturwissenschaftlichen Bib reserviert, nämlich Raum 2 um 10:30 bis 12 Uhr

**Comment by Arucis** [comment]
Am 11.7

**Comment by MrOerni** [comment]
Genau dort habe ich eine Vorlesung.
Mo geht ab 12

**Comment by tuncerd101** [comment]
Wir haben die Reservierung vom raum verlängert bis 13 uhr

**Comment by MrOerni** [comment]
Gut, dann morgen 12:15 im Raum 2. 
Das ganze dauert nicht lange.

Wie gesagt: Nur vorstellen was hat das Team erreicht. Wie war die Planung? Ging das gut?
Was ist noch zu machen..

Das sollte alles nicht solange dauern. 10-30min höchstens
